apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app  # Matches the "app" label in the deployment.yaml
  ports:
    - protocol: TCP
      port: 80  # External port (LoadBalancer or NodePort will expose this)
      targetPort: 8080  #  matches the containerPort in the deployment.yaml
      nodePort: 30080  # To specify a node port or let Kubernetes choose one
  type: NodePort  # Change from LoadBalancer to NodePort
